### ISSUE TITLE
ThreadStats doesn't flush remaining metrics

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/datadogpy#217] opened 2017-07-06 19:30 UTC
When doing the following, no metrics are reported.

```python
from datadog import initialize
from datadog import ThreadStats


initialize(api_key="api_key", app_key="app_key")

stats = ThreadStats()
stats.start()
stats.gauge("test.foo", 1)
stats.flush()
stats.stop()
```

It appears that when we flush `stats` it'll only flush metrics that belong to previous rollup intervals and will always ignore the current interval.

I can fix this issue by doing the following to trick it to think that more time has past.

```python
import time

stats.flush(time.time() + 10)
```

This seems to be an issue for short running environments like `lambda` functions.

**Comment by yannmh** [comment] 2017-08-07 20:35
This would be fixed with https://github.com/DataDog/datadogpy/pull/221. Please let me know how that would work for you 🙇

**Comment by austinmills** [comment] 2017-12-21 22:23
We're running into this right now for short-lived python code. It looks like there's a PR?

**Comment by sylvestre** [comment] 2018-02-01 08:56
@LeoCavaille ^^ if you can help!

**Comment by irabinovitch** [comment] 2018-02-02 21:06
@austinmills Apologies for the delay #221 is now merged.

**Comment by jmehnle** [comment] 2019-03-06 19:59
@brettlangdon, can you still reproduce the faulty behavior or does the merge of #221 resolve this issue?

**Comment by gzussa** [comment] 2019-05-27 16:38
Seems this is working now

**Closed by gzussa** 2019-05-27 16:38 UTC

**Comment by carlosrochap** [comment] 2019-07-11 17:06
I'm still seeing this issue.  Doing stats.flush(time.time() + 10) seems to fix it

**Comment by dabcoder** [comment] 2019-11-07 13:02
@carlosrochap Sorry for the delay. Is that definitely fixed with that option set to `False`? Let us know if we need to reopen this issue and look into it.

**Comment by carlosrochap** [comment] 2019-11-07 22:14
@dabcoder nope, I decided to stop using this and decided to use the agent running on k8s
