### ISSUE TITLE
Install error under PyPy 5.0.1

### ISSUE THREAD

**Issue by radzhome** [DataDog/datadogpy#248] opened 2018-01-19 04:57 UTC
When installing datadog 0.17.0 under PyPy, I experienced the following syntax error:

```
Installing collected packages: boto, datadog, decorator, elasticsearch, pika, setproctitle, redis, unicodecsv, PyMySQL, pytz, requests, simplejson, urllib3, chardet, idna, certifi
  Running setup.py install for boto

    warning: no files found matching 'boto/mturk/test/*.doctest'
    warning: no files found matching 'boto/mturk/test/.gitignore'
    changing mode of build/scripts-2.7/sdbadmin from 664 to 775
    changing mode of build/scripts-2.7/elbadmin from 664 to 775
    changing mode of build/scripts-2.7/cfadmin from 664 to 775
    changing mode of build/scripts-2.7/s3put from 664 to 775
    changing mode of build/scripts-2.7/fetch_file from 664 to 775
    changing mode of build/scripts-2.7/launch_instance from 664 to 775
    changing mode of build/scripts-2.7/list_instances from 664 to 775
    changing mode of build/scripts-2.7/taskadmin from 664 to 775
    changing mode of build/scripts-2.7/kill_instance from 664 to 775
    changing mode of build/scripts-2.7/bundle_image from 664 to 775
    changing mode of build/scripts-2.7/pyami_sendmail from 664 to 775
    changing mode of build/scripts-2.7/lss3 from 664 to 775
    changing mode of build/scripts-2.7/cq from 664 to 775
    changing mode of build/scripts-2.7/route53 from 664 to 775
    changing mode of build/scripts-2.7/cwutil from 664 to 775
    changing mode of build/scripts-2.7/instance_events from 664 to 775
    changing mode of build/scripts-2.7/asadmin from 664 to 775
    changing mode of build/scripts-2.7/glacier from 664 to 775
    changing mode of build/scripts-2.7/mturk from 664 to 775
    changing mode of build/scripts-2.7/dynamodb_dump from 664 to 775
    changing mode of build/scripts-2.7/dynamodb_load from 664 to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/sdbadmin to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/elbadmin to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/cfadmin to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/s3put to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/fetch_file to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/launch_instance to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/list_instances to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/taskadmin to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/kill_instance to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/bundle_image to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/pyami_sendmail to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/lss3 to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/cq to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/route53 to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/cwutil to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/instance_events to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/asadmin to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/glacier to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/mturk to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/dynamodb_dump to 775
    changing mode of /usr/local/virtualenvs/pipeline_pypy/bin/dynamodb_load to 775
  Running setup.py install for datadog
      File "/usr/local/virtualenvs/pipeline_pypy/site-packages/datadog/dogstatsd/context_async.py", line 16
        async def wrapped_co(*args, **kwargs):
        ^
    SyntaxError: invalid syntax


    Installing dog script to /usr/local/virtualenvs/pipeline_pypy/bin
    Installing dogwrap script to /usr/local/virtualenvs/pipeline_pypy/bin
  Running setup.py install for decorator

    warning: no files found matching 'documentation.pdf'
```

Any plans to support PyPy?

**Comment by yannmh** [comment] 2018-02-02 02:53
@radzhome PyPy should be supported. It's also included in our CI to prevent any regression that would break the compatibility.

I just ran a quick test to confirm:

```
$ python --version
Python 2.7.10 (bbd45126bc69, Mar 18 2016, 21:19:56)
[PyPy 5.0.1 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)]

$ python setup.py test

----------------------------------------------------------------------
Ran 41 tests in 25.533s

OK
```


Running `python setup.py install` shows the same output as the one you copied. It is only a warning, and should not prevent the installation from succeeding. Could you confirm that point?
 
Regarding the "problematic" snippet, it can only be called on Python 3.5+, c.f. https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/context.py#L12

**Comment by gzussa** [comment] 2019-05-27 16:55
Closing this since it's more than 1 year old

**Closed by gzussa** 2019-05-27 16:55 UTC
