### ISSUE TITLE
Unmute all monitors fails with 403 forbidden

### ISSUE THREAD

**Issue by samanthadrago** [DataDog/datadogpy#49] opened 2015-05-18 19:19 UTC
`dog monitors unmute_all` fails with 403 forbidden error:
```
dog monitor unmute_all
Traceback (most recent call last):
  File "/home/vagrant/dogweb/python/bin/dog", line 9, in <module>
    load_entry_point('datadog==0.4.0', 'console_scripts', 'dog')()
  File "/home/vagrant/dogweb/python/local/lib/python2.7/site-packages/datadog/dogshell/__init__.py", line 71, in main
    args.func(args)
  File "/home/vagrant/dogweb/python/local/lib/python2.7/site-packages/datadog/dogshell/monitor.py", line 177, in _unmute_all
    res = api.Monitor.unmute_all()
  File "/home/vagrant/dogweb/python/local/lib/python2.7/site-packages/datadog/api/monitors.py", line 95, in unmute_all
    return super(Monitor, cls)._trigger_class_action('POST', 'unmute_all')
  File "/home/vagrant/dogweb/python/local/lib/python2.7/site-packages/datadog/api/base.py", line 411, in _trigger_class_action
    return HTTPClient.request(method, cls._class_url + "/" + name, params)
  File "/home/vagrant/dogweb/python/local/lib/python2.7/site-packages/datadog/api/base.py", line 118, in request
    result.raise_for_status()
  File "/home/vagrant/dogweb/python/local/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden
```
It worked as expected (before the dogrc file was configured) by passing keys in the request itself, like this `dog --api-key {key} --application-key {key}  monitor unmute_all`. Once that file is configured, it doesn't work anymore.

**Comment by yannmh** [comment] 2015-05-19 01:43
Thanks for reporting @samanthadrago.

I don't think it's related with `~/.dogrc` configuration file: if it really is, then I am unable to reproduce.
On my side, I get a `403` return code when I try to unmute monitors while no monitor is in a mute state. Thus, this snippet works fine:
```shell
dog monitor mute_all
dog monitor unmute_all
```
Could you please confirm that your issue is the same ? Thank you

**Comment by samanthadrago** [comment] 2015-05-19 21:49
@yannmh You're right. The error comes up when trying to `unmute_all` if no monitors are muted - nothing to do with `~/.dogrc` at all.

**Comment by yannmh** [comment] 2015-05-19 21:53
Thanks for the confirmation. Closing the issue.

**Closed by yannmh** 2015-05-19 21:53 UTC

**Comment by samanthadrago** [comment] 2015-05-27 21:19
@yannmh the user discovered confusing behavior via the API related to this and wanted to clarify:

If a few monitors are muted, `dog monitor unmute_all` does not work - it returns the above error. The command only appears to work if ALL the monitors are muted (i.e. Mute All has been selected) - is this expected? If so, could we document it or add better error handling to explain why it doesn't work?

**Comment by wang-arthur** [comment] 2015-05-27 21:31
@samanthadrago, `mute_all` and `unmute_all` should work independently of the muting of individual monitors, because "Mute all" is a global setting (also known as a `downtime` over `*`). I can see how `unmute_all` in particular might be misleading, because it doesn't actually clear all mute settings on individual monitors. Instead, it disables the global mute setting.

**Comment by samanthadrago** [comment] 2015-05-27 21:33
@wang-arthur thank you for clarifying this!
