### ISSUE TITLE
How to disable datadog on the local dev environment ?

### ISSUE THREAD

**Issue by mohamedrez** [DataDog/datadogpy#296] opened 2018-09-17 09:15 UTC
Whenever I run the local server on django I get this error:
```
INFO [/usr/local/lib/python2.7/site-packages/datadog/dogstatsd/base.py:294] - Error submitting packet, dropping the packet and closing the socket
```

Is there a way to disable it on the local dev env ?

**Comment by zippolyte** [comment] 2019-06-03 12:54
Hello @mohamedrez,

Sorry for not answering sooner.
What exactly are you trying to do ? I'm not sure I understand what the problem is. You don't have a dogstatsd server running on your local machine, and you want to skip sending dogstatsd messages right ?
There is no functionality like that in the library currently. One way you could work around that would be to mock the dogstatsd object when you're on your local dev environment. Would that work for you ?

**Comment by zippolyte** [comment] 2019-06-12 15:02
@mohamedrez 
I don't think this is an issue that we should solve in the code. 
This a setup problem as you don't have a dogstatsd server running but are still trying to submit metrics. It's looks more like something to add in your code to detect when you're in your dev environment and in that case mock the dogstatsd object
Closing

**Closed by zippolyte** 2019-06-12 15:02 UTC
